/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aplicacion;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author quiji
 */
public class Factura extends javax.swing.JFrame {
        Connection connection = DBConnection.connection;
    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
        this.setLocationRelativeTo(null);
        actualizarTabla();
    }
    
    public void actualizarTabla() {
        String[] nombreColumnas = {"Codigo","Platillo","Codigo de Platillo","Cliente","NIT","Vendedor"};
        String[] registros = new String[6];
        
        DefaultTableModel model = new DefaultTableModel(null, nombreColumnas);
        
        String productos = "SELECT * FROM Factura";
        
        try (PreparedStatement preSt = connection.prepareStatement(productos)) {
            ResultSet result = preSt.executeQuery();
            
            while(result.next()) {
                registros[0] = result.getString("NumeroFactura");
                registros[1] = result.getString("Platillo");
                registros[2] = result.getString("CodigoPlatillo");
                registros[3] = result.getString("NombreCliente");
                registros[4] = result.getString("NITCliente");
                registros[5] = result.getString("Vendedor");
                model.addRow(registros);
            }
            TablaFactura.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al actualizar la tabla: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtPlatillo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtCodigoP = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtNombreC = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtNITC = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtVendedor = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btCrearF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFactura = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(91, 33, 129));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(63, 25, 88));
        jLabel1.setText("F A C T U R A ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(81, 81, 81))
        );

        txtNumeroF.setBackground(new java.awt.Color(91, 33, 129));
        txtNumeroF.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtNumeroF.setForeground(new java.awt.Color(204, 204, 204));
        txtNumeroF.setText("Numero de Factura");
        txtNumeroF.setBorder(null);
        txtNumeroF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumeroFFocusGained(evt);
            }
        });
        txtNumeroF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroFActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("N.° de Factura");

        txtPlatillo.setBackground(new java.awt.Color(91, 33, 129));
        txtPlatillo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtPlatillo.setForeground(new java.awt.Color(204, 204, 204));
        txtPlatillo.setText("Platillo");
        txtPlatillo.setBorder(null);
        txtPlatillo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPlatilloFocusGained(evt);
            }
        });

        txtCodigoP.setBackground(new java.awt.Color(91, 33, 129));
        txtCodigoP.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtCodigoP.setForeground(new java.awt.Color(204, 204, 204));
        txtCodigoP.setText("Codigo de Platillo");
        txtCodigoP.setBorder(null);
        txtCodigoP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoPFocusGained(evt);
            }
        });

        txtNombreC.setBackground(new java.awt.Color(91, 33, 129));
        txtNombreC.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtNombreC.setForeground(new java.awt.Color(204, 204, 204));
        txtNombreC.setText("Nombre de Cliente");
        txtNombreC.setBorder(null);
        txtNombreC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreCFocusGained(evt);
            }
        });

        txtNITC.setBackground(new java.awt.Color(91, 33, 129));
        txtNITC.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtNITC.setForeground(new java.awt.Color(204, 204, 204));
        txtNITC.setText("NITCliente");
        txtNITC.setBorder(null);
        txtNITC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNITCFocusGained(evt);
            }
        });

        txtVendedor.setBackground(new java.awt.Color(91, 33, 129));
        txtVendedor.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtVendedor.setForeground(new java.awt.Color(204, 204, 204));
        txtVendedor.setText("Vendedor");
        txtVendedor.setBorder(null);
        txtVendedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVendedorFocusGained(evt);
            }
        });

        btCrearF.setBackground(new java.awt.Color(91, 33, 129));
        btCrearF.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btCrearF.setForeground(new java.awt.Color(204, 204, 204));
        btCrearF.setText("Crear Factura");
        btCrearF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearFActionPerformed(evt);
            }
        });

        TablaFactura.setBackground(new java.awt.Color(91, 33, 129));
        TablaFactura.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        TablaFactura.setForeground(new java.awt.Color(204, 204, 204));
        TablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaFactura.setGridColor(new java.awt.Color(211, 211, 211));
        jScrollPane1.setViewportView(TablaFactura);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(txtNumeroF))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(txtPlatillo, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3)
                            .addComponent(txtCodigoP, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreC, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jSeparator4))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNITC, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(jSeparator5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6)
                            .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btCrearF)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNITC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                            .addComponent(jSeparator5)
                            .addComponent(jSeparator6)
                            .addComponent(jSeparator3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeroF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                            .addComponent(jSeparator2))))
                .addGap(18, 18, 18)
                .addComponent(btCrearF)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroFActionPerformed

    }//GEN-LAST:event_txtNumeroFActionPerformed

    private void txtNumeroFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFFocusGained
        txtNumeroF.setText("");
    }//GEN-LAST:event_txtNumeroFFocusGained

    private void txtPlatilloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlatilloFocusGained
        txtPlatillo.setText("");
    }//GEN-LAST:event_txtPlatilloFocusGained

    private void txtCodigoPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoPFocusGained
        txtCodigoP.setText("");
    }//GEN-LAST:event_txtCodigoPFocusGained

    private void txtNombreCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreCFocusGained
        txtNombreC.setText("");
    }//GEN-LAST:event_txtNombreCFocusGained

    private void txtNITCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNITCFocusGained
        txtNITC.setText("");
    }//GEN-LAST:event_txtNITCFocusGained

    private void txtVendedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVendedorFocusGained
        txtVendedor.setText("");
    }//GEN-LAST:event_txtVendedorFocusGained

    private void btCrearFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearFActionPerformed
        String numerof, platillo, codigop, nombrec, nitc, vendedor;
        numerof = txtNumeroF.getText();
        platillo = txtPlatillo.getText();
        codigop = txtCodigoP.getText();
        nombrec = txtNombreC.getText();
        nitc = txtNITC.getText();
        vendedor = txtVendedor.getText();
        
        String insert = "INSERT INTO Factura VALUES(?,?,?,?,?,?)";
        try(PreparedStatement preSt = connection.prepareStatement(insert)) {
            preSt.setString(1, numerof);
            preSt.setString(2, platillo);
            preSt.setString(3, codigop);
            preSt.setString(4, nombrec);
            preSt.setString(5, nitc);
            preSt.setString(6, vendedor);
            
            preSt.executeUpdate();
            
             actualizarTabla();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al realizar la inserción: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCrearFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaFactura;
    private javax.swing.JButton btCrearF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField txtCodigoP;
    private javax.swing.JTextField txtNITC;
    private javax.swing.JTextField txtNombreC;
    private javax.swing.JTextField txtNumeroF;
    private javax.swing.JTextField txtPlatillo;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables
}
