/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aplicacion;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quiji
 */
public class Reporte extends javax.swing.JFrame {
        Connection connection = DBConnection.connection;
    /**
     * Creates new form Reporte
     */
    public Reporte() {
        initComponents();
        this.setLocationRelativeTo(null);
        actualizarTabla1();
    }
    
    public void actualizarTabla1(){
        String[] nombreColumnas = {"Nombre de Platillo","Cantidad de ventas"};
        String[] registros = new String[2];
        
        int posicion = cmbReportes.getSelectedIndex();
        String reporte;
        
        switch(posicion) {
            case 0:
                reporte = "SELECT Factura.NombrePlatillo, COUNT(Factura.NombrePlatillo) FROM Factura INNER JOIN Platillo ON Factura.NombrePlatillo = Platillo.NombrePlatillo WHERE Platillo.TipoPlatillo = 'Desayuno' GROUP BY NombrePlatillo ORDER BY COUNT(Factura.NombrePlatillo) DESC LIMIT 5";
                break;
            case 1:
                reporte = "SELECT Factura.NombrePlatillo, COUNT(Factura.NombrePlatillo) FROM Factura INNER JOIN Platillo ON Factura.NombrePlatillo = Platillo.NombrePlatillo WHERE Platillo.TipoPlatillo = 'Fuertes' GROUP BY NombrePlatillo ORDER BY COUNT(Factura.NombrePlatillo) DESC LIMIT 5";
                break;
            default:
                reporte = "SELECT Factura.NombrePlatillo, COUNT(Factura.NombrePlatillo) FROM Factura INNER JOIN Platillo ON Factura.NombrePlatillo = Platillo.NombrePlatillo WHERE Platillo.TipoPlatillo = 'Desayuno' GROUP BY NombrePlatillo ORDER BY COUNT(Factura.NombrePlatillo) DESC LIMIT 5";
                break;
        }
        
         DefaultTableModel model = new DefaultTableModel(null, nombreColumnas);
               
        try (PreparedStatement preSt = connection.prepareStatement(reporte)) {
            ResultSet result = preSt.executeQuery();
            
            while(result.next()) {
                registros[0] = result.getString("NombrePlatillo");
                registros[1] = result.getString("COUNT(Factura.NombrePlatillo)");
                model.addRow(registros);
            }
            TablaReportes.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al actualizar la tabla: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void actualizarTabla2(){
        String[] nombreColumnas = {"No.° Factura","Nombre","Codigo","Precio","Cliente","NIT CLiente","Vendedor"};
        String[] registros = new String[7];
            
        int posicion = cmbReportes.getSelectedIndex();
        String reporte;
        
        switch(posicion) {
            case 2:
                reporte = "SELECT * FROM Factura WHERE Precio > 40 ORDER BY Precio";
                break;
            case 3:
                reporte = "SELECT * FROM Factura WHERE Precio < 40 ORDER BY Precio;";
                break;
            default:
                reporte = "SELECT * FROM Factura WHERE Precio > 40 ORDER BY Precio";
                break;
        }
        
        DefaultTableModel model = new DefaultTableModel(null, nombreColumnas);
               
        try (PreparedStatement preSt = connection.prepareStatement(reporte)) {
            ResultSet result = preSt.executeQuery();
            
            while(result.next()) {
                registros[0] = result.getString("NumeroFactura");
                registros[1] = result.getString("CodigoPlatillo");
                registros[2] = result.getString("NombrePlatillo");
                registros[3] = result.getString("Precio");
                registros[4] = result.getString("NombreCliente");
                registros[5] = result.getString("NITCliente");
                registros[6] = result.getString("Vendedor");
                model.addRow(registros);
            }
            TablaReportes.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al actualizar la tabla: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbReportes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btGenerarReporte = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaReportes = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(91, 33, 129));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(63, 25, 88));
        jLabel1.setText("R E P O R T E S");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(92, 92, 92))
        );

        cmbReportes.setBackground(new java.awt.Color(91, 33, 129));
        cmbReportes.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cmbReportes.setForeground(new java.awt.Color(204, 204, 204));
        cmbReportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Top 5 desayunos más vendidos", "Top 5 platos fuertes más vendidios", "Ventas mayores a Q40.00", "Ventas Menores a Q40.00" }));
        cmbReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbReportesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Repostes");

        btGenerarReporte.setBackground(new java.awt.Color(91, 33, 129));
        btGenerarReporte.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btGenerarReporte.setForeground(new java.awt.Color(204, 204, 204));
        btGenerarReporte.setText("Generar Reporte");
        btGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenerarReporteActionPerformed(evt);
            }
        });

        TablaReportes.setBackground(new java.awt.Color(91, 33, 129));
        TablaReportes.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TablaReportes.setForeground(new java.awt.Color(204, 204, 204));
        TablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaReportes);

        jButton2.setBackground(new java.awt.Color(91, 33, 129));
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 671, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(btGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGenerarReporte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbReportesActionPerformed

    private void btGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerarReporteActionPerformed
        int posicion = cmbReportes.getSelectedIndex();
        
        switch(posicion) {
            case 0:
                actualizarTabla1();
                break;
            case 1:
                actualizarTabla1();
                break;
            case 2:
                actualizarTabla2();
                break;
            case 3:
                actualizarTabla2();
                break;
            default:
                
                break;
        }
    }//GEN-LAST:event_btGenerarReporteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        MenuAdministrador m1 = new MenuAdministrador();
        m1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaReportes;
    private javax.swing.JButton btGenerarReporte;
    private javax.swing.JComboBox<String> cmbReportes;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
